### ISSUE TITLE
Talk proposal -- Firefly

### ISSUE THREAD

**Issue by agurvich** [vast-seminars/talk-proposals#1]
### Name of software library or topic
Firefly: a browser-based interactive 3D data visualization tool for millions of data points

### URL to software repository
https://github.com/ageller/Firefly

### Name of person who will give the talk
[Alex Gurvich](https://alexbgurvi.ch)

### Brief abstract
Firefly is a new browser-based interactive tool for visualizing 3D particle data sets. On a typical personal computer, Firefly can simultaneously render and enable real-time interactions with > ~10 million particles, and can interactively explore datasets with billions of particles using the included custom-built octree render engine. Once created, viewing a Firefly visualization requires no installation and is immediately usable in most modern internet browsers simply by visiting a URL. As a result, a Firefly visualization works out-of-the-box on most devices including smartphones and tablets. Firefly is primarily developed for researchers to explore their own data, but can also be useful to communicate results to researchers/collaborators and as an effective public outreach tool. Every element of the user interface can be customized and disabled, enabling easy adaptation of the same visualization for different audiences with little additional effort. A gallery of interactive live demos is available at https://alexbgurvi.ch/Firefly.

**Comment by ketozhang** [comment]
Disambiguation

Not to be confused with https://github.com/Caltech-IPAC/firefly

**Comment by teuben** [comment]
Sounds much like glnemo2, which i use a lot. I really like glnemo2 since it can read a whole bunch of nbody formats, plus it can 3dview a fits cube, which works remarkably well. Still, I'd love to see firefly in action!

If we do 2 talks per session, maybe we should invite  Jean-Charles (from Marseille) for the 2nd half.

**Comment by agurvich** [comment]
Looking at some of the demo movies on the GLnemo2 site, it does look very similar! Would make for a great general nbody viz discussion.
