### ISSUE TITLE
Lighting talk proposal: LINCC - lsstseries

### ISSUE THREAD

**Issue by nevencaplar** [vast-seminars/talk-proposals#10]
### Name of software library or topic

lsstseries  - a library for accessing and analyzing time-domain data from the LSST survey 

### URL to software repository

https://github.com/lincc-frameworks/lsstseries
https://github.com/lincc-frameworks/docs/wiki/Time-series-data-at-LSST-scale

### Name of person who will give the talk

Neven Caplar

### Brief abstract

LINCC Frameworks is a program to support the LSST community in developing their analyses in collaboration with professional software engineers and data scientists. I will describe our recently started effort to create libraries for analyzing time-domain data from the LSST survey. We aim to focus on ease of use (e.g., as LightKurve) & scalability of algorithms to accommodate the size and complexity of LSST data.

**Comment by zingale** [comment]
presented 12/21
