### ISSUE TITLE
Talk proposal: Multidimensional Stellar Grids (MSG)

### ISSUE THREAD

**Issue by warrickball** [vast-seminars/talk-proposals#14]
### Name of software library or topic

Multidimensional Stellar Grids (MSG)

### URL to software repository

https://github.com/rhdtownsend/msg

### Name of person who will give the talk

Rich Townsend?

### Brief abstract

> MSG (Multidimensional Stellar Grids) is a library that synthesizes astrophysical spectra and photometric colors via interpolation in pre-calculated grids. Given a set of stellar atmospheric parameters (e.g., effective temperature, gravity and metallicity), MSG can calculate the specific intensity of the emergent radiation field as a function of wavelength and angle. It can also convolve these data with appropriate filters and response functions, to evaluate colors in a wide variety of photometric systems.

**Comment by zingale** [comment]
talk completed
