### ISSUE TITLE
Talk proposal: TARDIS: Temperature And Radiative Diffusion In Supernovae (and other tools)

### ISSUE THREAD

**Issue by warrickball** [vast-seminars/talk-proposals#27]
### Name of software library or topic

[TARDIS](https://tardis-sn.github.io/)

### URL to software repository

https://github.com/tardis-sn

### Name of person who will give the talk

https://tardis-sn.github.io/people/core/ ?

### Brief abstract

> TARDIS packages provide several tools for physics calculation and visualization to make your supernova research easier.

I'm proposing this because it looks like an interesting suite of tools that might be applicable more widely. E.g., could I use these tools to build Rosseland mean opacities (given an equation of state)?

**Comment by zingale** [comment]
we had a tardis talk in Nov 2022, so maybe it's too soon for a repeat?

**Comment by warrickball** [comment]
Ah, apologies for missing that. I don't think a repeat is necessary, given that there's [a recording](https://www.youtube.com/watch?v=tw-zZKxosGQ) on [the YouTube channel](https://www.youtube.com/@virtualastronomysoftwareta7988).
