### ISSUE TITLE
Talk proposal: SpECTRE elliptic solver

### ISSUE THREAD

**Issue by nilsvu** [vast-seminars/talk-proposals#28]
### Name of software library or topic

SpECTRE elliptic solver

### URL to software repository

https://github.com/sxs-collaboration/spectre

### Name of person who will give the talk

Nils L. Vu

### Brief abstract

I present the elliptic solver of the SpECTRE numerical relativity code, which is used to generate initial data for simulations of merging black holes and neutron stars. It's based on discontinuous Galerkin methods and task-based parallel implementations of Krylov-subspace iterative algorithms with a multigrid-Schwarz preconditioner.

**Comment by zingale** [comment]
talk was presented
