### ISSUE TITLE
Talk Proposal: Poseidon

### ISSUE THREAD

**Issue by jrober50** [vast-seminars/talk-proposals#29]
### Name of software library or topic
Poseidon

### URL to software repository
https://github.com/jrober50/Poseidon

### Name of person who will give the talk
Nick Roberts

### Brief abstract

Poseidon is a relativistic metric solver in development for use in core-collapse supernova (CCSN) simulations.  Currently, it is being used as part of the thornado CCSN framework. I will discuss the mixed method used to solve the xCFC metric system of equations and present results.

**Comment by zingale** [comment]
talk was presented
