### ISSUE TITLE
Talk proposal - lenstronomy

### ISSUE THREAD

**Issue by sibirrer** [vast-seminars/talk-proposals#4]
### Name of software library or topic
lenstronomy - a multi-purpose gravitational lensing software package

### URL to software repository
https://github.com/lenstronomy/lenstronomy

### Name of person who will give the talk
Simon Birrer

### Brief abstract
lenstronomy is a multi-purpose software package to model strong gravitational lenses. lenstronomy finds application for time-delay cosmography and measuring the expansion rate of the Universe, for quantifying lensing substructure to infer dark matter properties, morphological quantification of galaxies, quasar-host galaxy decomposition and much more.
lenstronomy is an Astropy-affiliated package and has recently moved to a project repository.
I will describe use cases that go beyond gravitational lensing, outline the design principles and highlight future developments/

**Comment by zingale** [comment]
presented 12/21

**Comment by sibirrer** [comment]
Thank you very much @zingale and the VAST team!
