### ISSUE TITLE
Talk proposal - NWelch

### ISSUE THREAD

**Issue by sdrastro** [vast-seminars/talk-proposals#6]
### Name of software library or topic

NWelch: python implementation of Welch's method for estimating the power spectra, complex cross-spectrum, magnitude-squared coherence, and phase spectrum of unevenly spaced, bivariate time series

### URL to software repository

https://github.com/sdrastro/NWelch

### Name of person who will give the talk

Sally Dodson-Robinson

### Brief abstract

NWelch uses Welch's method to estimate the power spectra, complex cross-spectrum, magnitude-squared coherence, and phase spectrum of bivariate time series with nonuniform observing cadence. For univariate time series, users can apply the Welch's power spectrum estimator or compute a nonuniform fast Fourier transform-based periodogram. Unlike Lomb-Scargle periodograms, Welch's power spectrum estimates have variance that decreases as the number of observations increases. NWelch options include tapering in the time domain and computing bootstrap false alarm levels. NWelch was designed for Doppler planet searches but may be applied to any type of time series.

**Comment by zingale** [comment]
presented 12/21
