### ISSUE TITLE
Talk proposal: Jdaviz

### ISSUE THREAD

**Issue by camipacifici** [vast-seminars/talk-proposals#7]
### Name of software library or topic
Jdaviz: An interactive visual data analysis tool for JWST in the Jupyter platform

### URL to software repository
https://github.com/spacetelescope/jdaviz

### Name of person who will give the talk
Camilla Pacifici

### Brief abstract
Jdaviz (JWST Data Analysis and Visualization) is a Python package developed at the Space Telescope Science Institute (STScI) to provide GUI-based visualization and interactive analysis capabilities. The package includes 4 tools: Specviz for 1D spectra, Mosviz for multi-object spectroscopy data, Cubeviz for cubes, and Imviz for imaging. The tools are designed to work within a Jupyter notebook cell, as a standalone desktop application, or as embedded windows within a website – all with nearly-identical user interfaces. Jdaviz has been designed specifically to support JWST use cases, but can be used for a wide range of astronomical data.

**Comment by zingale** [comment]
presented 12/21
